version: "3.7"

services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/
    networks:
      - app

  nginx:
    image: nginx:latest
    volumes:
      - ./public:/var/www/public
      - ./docker/laravel.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:8080"
    networks:
      - app

networks:
  app:
